# -*- coding: utf-8 -*-
"""generate_sexual_lexicon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jtFFGfkPpIt69TIrSvsyJBQAcBMk1zTe
"""

!pip install pandas openai

!python generate_sexual_lexicon.py --input "./Downloads/HateSpeechAllGender - Sheet3.csv" --outdir "."

# generate_sexual_lexicon.py
# -*- coding: utf-8 -*-
"""
Create lexicon and placeholders for sexual/adult terms from a CSV.

Outputs:
  - lexicon_sexual_adult.csv / .json
  - placeholders_sexual_adult.json
  - regex_patterns_sexual_adult.json
  - LEXICON_README_sexual_adult.txt

Usage:
  # This script is intended to be run directly in a Colab cell.
  # Input and output paths are defined within the script.

Notes:
  - Simple Tamil-aware normalization (keeps Tamil letters, digits, underscores).
  - N-grams: 1–3 grams with frequency.
  - Filtered to sexual/adult-related terms only (heuristic seeds + regex).
"""

import json
import os
import re
from collections import Counter
from itertools import tee

try:
    import pandas as pd
except ImportError:
    raise SystemExit("Please install pandas: pip install pandas")

# ------------------ Config ------------------
TAMIL_BLOCK = r"\u0B80-\u0BFF"
TA_CLASS = r"[஀-௿]"  # broad Tamil range

# Seed lists (edit/extend as you wish)
SEXUAL_THREAT = set("""கற்பழிக்கிறேன் கற்பழிப்பேன் கற்பழி வல்லுறவு கிழிக்கிறேன் கிழிப்பேன் துஷ்பிரயோகம் பாலியல் வன்முறை""".split())
SEXUAL_OBJECT = set("""உடம்பு முலை இடுப்பு கவர்ச்சி காமம் புணர்ச்சி உடலுறவு அழகு மாதரம் மங்கைமைகள்""".split())
SEXUAL_SLURS  = set("""ஒத்தா புண்டை வேசி கேவலம் அசிங்கம் காமுகி கள்ளி""".split())

# “Adult” (non-violent sexual content/industry words; include common English spillover too)
ADULT_GENERAL = set("""sex sexual sexy porn pornographic pornstar nude nudes xxx hot boobs breast body figure item""".split())

# Additional English stems we might see
EN_SEXUAL_STEMS = ("sex", "porn", "nude", "xxx", "rape")

# Regex stems (Tamil + English)
REGEX_PATTERNS = {
    "Sexual Threat": [
        rf"(கற்பழி|வல்லுறவு|கிழி){TA_CLASS}*",
        rf"(கற்பழிக்கிறேன்|கற்பழிப்பேன்|கிழிக்கிறேன்)"
    ],
    "Sexual Objectification": [
        rf"(உடம்பு|முலை|இடுப்பு|காமம்|கவர்ச்சி){TA_CLASS}*",
        rf"{TA_CLASS}+ அழகு {TA_CLASS}+"
    ],
    "Sexual/Adult Slur or Content": [
        rf"(ஒத்தா|புண்டை|வேசி|அசிங்கம்|கேவலம்)",
        r"(sex|sexual|sexy|porn|xxx|nude|rape)"
    ],
}

# ---------------- Helpers -------------------
def normalize_text(s: str) -> str:
    """Keep Tamil letters, digits, underscores; remove other punctuation; collapse spaces."""
    s = "" if not isinstance(s, str) else s
    s = re.sub(rf"[^\w\s{TAMIL_BLOCK}]", " ", s, flags=re.UNICODE)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def detect_text_column(df) -> str:
    """Find a likely text column, or default to the first column."""
    candidates = [c for c in df.columns if str(c).strip().lower() in {"text", "utterance", "comment", "sentence"}]
    return candidates[0] if candidates else df.columns[0]

def ngrams(tokens, n):
    iters = tee(tokens, n)
    for i, it in enumerate(iters):
        for _ in range(i):
            next(it, None)
    return zip(*iters)

def extract_top_ngrams(series_texts, topk=300, n_values=(1,2,3)):
    counter = Counter()
    for t in series_texts:
        if not isinstance(t, str):
            continue
        toks = t.split()
        for n in n_values:
            for ng in ngrams(toks, n):
                phrase = " ".join(ng)
                if len(phrase) < 2:
                    continue
                if re.fullmatch(r"\d+", phrase):
                    continue
                counter[phrase] += 1
    return counter.most_common(topk)

def is_sexual_or_adult_phrase(phrase: str) -> str | None:
    """
    Return subcategory if the phrase is sexual/adult.
    Subcategories:
      - Sexual Threat
      - Sexual Objectification
      - Sexual/Adult Slur or Content
    """
    toks = set(phrase.split())
    # fast checks
    if toks & SEXUAL_THREAT:
        return "Sexual Threat"
    if toks & SEXUAL_OBJECT:
        return "Sexual Objectification"
    if (toks & SEXUAL_SLURS) or (toks & ADULT_GENERAL):
        return "Sexual/Adult Slur or Content"

    # regex/stem checks
    if re.search(r"(கற்பழி|வல்லுறவு|கிழி)", phrase):
        return "Sexual Threat"
    if re.search(r"(முலை|இடுப்பு|காமம்|உடம்பு|கவர்ச்சி)", phrase):
        return "Sexual Objectification"
    if re.search(r"(ஒத்தா|புண்டை|வேசி|அசிங்கம்|கேவலம்)", phrase):
        return "Sexual/Adult Slur or Content"
    if any(stem in phrase.lower() for stem in EN_SEXUAL_STEMS):
        return "Sexual/Adult Slur or Content"

    return None

def to_placeholders(phrase: str) -> str:
    """
    Replace known tokens by placeholders:
      {SEXUAL_THREAT}, {SEXUAL_ATTR}, {SEX_ADULT_SLUR}, {LATIN_WORD}, {NUMBER}
    """
    out = []
    for w in phrase.split():
        lw = w.lower()
        repl = None
        if lw in SEXUAL_THREAT:
            repl = "{SEXUAL_THREAT}"
        elif lw in SEXUAL_OBJECT:
            repl = "{SEXUAL_ATTR}"
        elif lw in SEXUAL_SLURS or lw in ADULT_GENERAL or any(lw.startswith(s) for s in EN_SEXUAL_STEMS):
            repl = "{SEX_ADULT_SLUR}"
        elif re.fullmatch(r"[A-Za-z]+", w):
            repl = "{LATIN_WORD}"
        elif re.fullmatch(r"\d+", w):
            repl = "{NUMBER}"
        out.append(repl if repl else w)
    return " ".join(out)

# --------------- Main --------------------
def main():
    # Define input and output paths directly
    input_file = "./HateSpeechAllGender - Sheet3.csv"
    outdir = "."
    topk = 300

    os.makedirs(outdir, exist_ok=True)

    # Load CSV robustly
    df = None
    last_err = None
    for enc in ["utf-8", "utf-8-sig", "iso-8859-1"]:
        try:
            df = pd.read_csv(input_file, encoding=enc)
            break
        except Exception as e:
            last_err = e
    if df is None:
        raise RuntimeError(f"Could not read CSV. Last error: {last_err}")

    # Clean
    df = df.dropna(axis=1, how="all")
    text_col = detect_text_column(df)
    df["_text_norm"] = df[text_col].map(normalize_text)

    # Build n-gram lexicon (1–3 grams), then filter to sexual/adult
    top_all = extract_top_ngrams(df["_text_norm"], topk=topk, n_values=(1,2,3))
    kept = []
    for ng, freq in top_all:
        sub = is_sexual_or_adult_phrase(ng)
        if sub:
            kept.append({"subcategory": sub, "ngram": ng, "frequency": int(freq)})

    # Save lexicon
    out_csv = os.path.join(outdir, "lexicon_sexual_adult.csv")
    out_json = os.path.join(outdir, "lexicon_sexual_adult.json")
    if kept:
        pd.DataFrame(kept).sort_values(
            by=["subcategory","frequency","ngram"], ascending=[True, False, True]
        ).to_csv(out_csv, index=False)
        pd.DataFrame(kept).to_json(out_json, orient="records", force_ascii=False, indent=2)
    else:
        # still write empty files
        pd.DataFrame(columns=["subcategory","ngram","frequency"]).to_csv(out_csv, index=False)
        with open(out_json, "w", encoding="utf-8") as f:
            json.dump([], f, ensure_ascii=False, indent=2)

    # Build placeholders per subcategory
    placeholders = {}
    if kept:
        df_lex = pd.DataFrame(kept)
        for sub, subdf in df_lex.groupby("subcategory"):
            phs = [to_placeholders(x) for x in subdf["ngram"].head(200)]
            # deduplicate
            seen, keep = set(), []
            for p in phs:
                if p not in seen:
                    seen.add(p); keep.append(p)
            placeholders[sub] = {
                "example_placeholders": keep[:60],
                "notes": [
                    "Placeholders: {SEXUAL_THREAT}, {SEXUAL_ATTR}, {SEX_ADULT_SLUR}, {LATIN_WORD}, {NUMBER}."
                ]
            }
    out_ph = os.path.join(outdir, "placeholders_sexual_adult.json")
    with open(out_ph, "w", encoding="utf-8") as f:
        json.dump(placeholders, f, ensure_ascii=False, indent=2)

    # Regex patterns
    out_pat = os.path.join(outdir, "regex_patterns_sexual_adult.json")
    with open(out_pat, "w", encoding="utf-8") as f:
        json.dump(REGEX_PATTERNS, f, ensure_ascii=False, indent=2)

    # README
    out_readme = os.path.join(outdir, "LEXICON_README_sexual_adult.txt")
    readme = f"""LEXICON (Sexual & Adult terms only)

Source: {input_file}
Detected text column: {text_col}

Subcategories:
- Sexual Threat
- Sexual Objectification
- Sexual/Adult Slur or Content

Files:
1) lexicon_sexual_adult.csv / .json
2) placeholders_sexual_adult.json
3) regex_patterns_sexual_adult.json

Placeholders:
- {{SEXUAL_THREAT}}    e.g., கற்பழிக்கிறேன், வல்லுறவு, கிழிக்கிறேன்
- {{SEXUAL_ATTR}}      e.g., முலை, இடுப்பு, காமம், உடம்பு
- {{SEX_ADULT_SLUR}}   e.g., ஒத்தா, புண்டை, வேசி, sex, porn, xxx
- {{LATIN_WORD}}, {{NUMBER}}

Notes:
- Tokenization: whitespace (simple). You can extend seeds and rerun.
- To adjust coverage, edit the seed lists in the script and run again.
"""
    with open(out_readme, "w", encoding="utf-8") as f:
        f.write(readme)

    print("Saved:")
    print(" ", out_csv)
    print(" ", out_json)
    print(" ", out_ph)
    print(" ", out_pat)
    print(" ", out_readme)

if __name__ == "__main__":
    main()

"""## Review results

### Subtask:
Display a sample of the original text and the text with placeholders to verify the transformation.

**Reasoning**:
Display the head of the DataFrame to show the original text and the text with placeholders, then display a few random rows to further verify the transformation.
"""

import pandas as pd

# Display the head of the DataFrame
print("Head of the DataFrame:")
display(df[[' Text', 'text_with_placeholders']].head())

# Display a few random rows
print("\nRandom rows from the DataFrame:")
display(df[[' Text', 'text_with_placeholders']].sample(5))

# Ensure lexicon_df is available
if 'lexicon_df' in locals():
    # Sort by frequency in descending order and display the top 10
    top_10_ngrams = lexicon_df.sort_values(by='frequency', ascending=False).head(10)
    display(top_10_ngrams)
else:
    print("lexicon_df not found. Please make sure the cell reading lexicon_sexual_adult.csv has been run successfully.")

import json

# Ensure the placeholders_json variable is available from the previous cell's execution
if 'placeholders_json' in locals():
    print(json.dumps(placeholders_json, indent=2, ensure_ascii=False))
else:
    # If the variable is not found, try to load the file again
    try:
        with open("placeholders_sexual_adult.json", "r", encoding="utf-8") as f:
            placeholders_json = json.load(f)
        print(json.dumps(placeholders_json, indent=2, ensure_ascii=False))
    except FileNotFoundError:
        print("placeholders_sexual_adult.json not found. Please make sure the script in cell MAA2VRshy2jk has been run successfully to generate this file.")
    except Exception as e:
        print(f"An error occurred while reading the file: {e}")

import json

try:
    with open("placeholders_sexual_adult.json", "r", encoding="utf-8") as f:
        placeholders_json = json.load(f)
    print(json.dumps(placeholders_json, indent=2, ensure_ascii=False))
except FileNotFoundError:
    print("placeholders_sexual_adult.json not found. Please make sure the script in cell MAA2VRshy2jk has been run successfully to generate this file.")
except Exception as e:
    print(f"An error occurred while reading the file: {e}")

import json

try:
    with open("lexicon_sexual_adult.json", "r", encoding="utf-8") as f:
        lexicon_json = json.load(f)
    print(json.dumps(lexicon_json, indent=2, ensure_ascii=False))
except FileNotFoundError:
    print("lexicon_sexual_adult.json not found. Please make sure the script in cell MAA2VRshy2jk has been run successfully to generate this file.")
except Exception as e:
    print(f"An error occurred while reading the file: {e}")

import pandas as pd

try:
    lexicon_df = pd.read_csv("lexicon_sexual_adult.csv")
    display(lexicon_df.head())
except FileNotFoundError:
    print("lexicon_sexual_adult.csv not found. Please make sure the script in cell MAA2VRshy2jk has been run successfully to generate this file.")
except Exception as e:
    print(f"An error occurred while reading the file: {e}")

try:
    with open("LEXICON_README_sexual_adult.txt", "r", encoding="utf-8") as f:
        readme_content = f.read()
    print(readme_content)
except FileNotFoundError:
    print("LEXICON_README_sexual_adult.txt not found. Please make sure the script in cell MAA2VRshy2jk has been run successfully to generate this file.")
except Exception as e:
    print(f"An error occurred while reading the file: {e}")

!zip lexicon_sexual_adult.zip lexicon_sexual_adult.csv lexicon_sexual_adult.json placeholders_sexual_adult.json regex_patterns_sexual_adult.json LEXICON_README_sexual_adult.txt

"""# Task
Apply the placeholder function to the text column of the dataframe `df` using the lexicon and regex patterns defined in cell `MAA2VRshy2jk` and display the results.

## Define placeholder application function

### Subtask:
Create a function that takes a text string as input and replaces identified sexual/adult terms with their respective placeholders based on the lexicon and regex patterns.

**Reasoning**:
Define the `apply_placeholders` function that utilizes the previously defined regex patterns and lexicon to replace sexual/adult terms with placeholders in a given text string.
"""

def apply_placeholders(text: str) -> str:
    """
    Replaces identified sexual/adult terms with their respective placeholders.

    Args:
        text: The input text string.

    Returns:
        The modified text string with placeholders.
    """
    if not isinstance(text, str):
        return text

    modified_text = text
    # Apply regex patterns first for broader matching
    for subcategory, patterns in REGEX_PATTERNS.items():
        placeholder = None
        if subcategory == "Sexual Threat":
            placeholder = "{SEXUAL_THREAT}"
        elif subcategory == "Sexual Objectification":
            placeholder = "{SEXUAL_ATTR}"
        elif subcategory == "Sexual/Adult Slur or Content":
            placeholder = "{SEX_ADULT_SLUR}"

        if placeholder:
            for pattern in patterns:
                # Use re.IGNORECASE for English terms in patterns
                flags = re.UNICODE
                if any(stem in pattern.lower() for stem in EN_SEXUAL_STEMS):
                    flags |= re.IGNORECASE
                modified_text = re.sub(pattern, placeholder, modified_text, flags=flags)

    # Apply lexicon matching (less aggressive, on normalized text)
    # Normalize the text for lexicon matching
    normalized_text = normalize_text(modified_text)
    tokens = normalized_text.split()
    processed_tokens = []
    i = 0
    while i < len(tokens):
        matched = False
        # Try matching 3-grams, then 2-grams, then 1-grams from the lexicon
        for n in [3, 2, 1]:
            if i + n <= len(tokens):
                ngram = " ".join(tokens[i : i + n])
                # Check if this ngram is in the lexicon and has a corresponding placeholder
                # We need to re-determine the placeholder based on the ngram's content
                sub = is_sexual_or_adult_phrase(ngram)
                if sub:
                    placeholder = None
                    if sub == "Sexual Threat":
                        placeholder = "{SEXUAL_THREAT}"
                    elif sub == "Sexual Objectification":
                        placeholder = "{SEXUAL_ATTR}"
                    elif sub == "Sexual/Adult Slur or Content":
                        placeholder = "{SEX_ADULT_SLUR}"

                    if placeholder:
                        processed_tokens.append(placeholder)
                        i += n
                        matched = True
                        break # Move to the next token after the matched ngram
        if not matched:
            # If no ngram matched, process the current token
            # Apply token-level placeholder logic (from to_placeholders, simplified)
            w = tokens[i]
            lw = w.lower()
            repl = None
            if lw in SEXUAL_THREAT:
                repl = "{SEXUAL_THREAT}"
            elif lw in SEXUAL_OBJECT:
                repl = "{SEXUAL_ATTR}"
            elif lw in SEXUAL_SLURS or lw in ADULT_GENERAL or any(lw.startswith(s) for s in EN_SEXUAL_STEMS):
                repl = "{SEX_ADULT_SLUR}"
            elif re.fullmatch(r"[A-Za-z]+", w):
                repl = "{LATIN_WORD}"
            elif re.fullmatch(r"\d+", w):
                repl = "{NUMBER}"
            processed_tokens.append(repl if repl else w)
            i += 1 # Move to the next token

    # This part is tricky: we applied lexicon matching on normalized text.
    # Reconstructing the original text with placeholders while preserving original spacing/punctuation
    # is complex without token-level alignment.
    # A simpler approach for this subtask is to just return the placeholder-applied normalized text.
    # For a more robust solution, a tokenization step that keeps track of original positions
    # would be needed before applying replacements.
    # Given the scope, we will return the placeholder-applied normalized text.
    return " ".join(processed_tokens)

"""## Apply placeholder function

### Subtask:
Apply the placeholder function to the text column of your input DataFrame to create a new column with the text containing placeholders.

**Reasoning**:
Apply the previously defined `apply_placeholders` function to the 'Text' column of the input DataFrame `df` and store the results in a new column named `text_with_placeholders`.
"""

# Assuming the input DataFrame is named 'df' and the text column is named 'Text'
# If the text column name is different, update 'Text' accordingly.
text_column_name = 'Text' # Based on the README output in cell 4dc5cc56

if text_column_name in df.columns:
    df['text_with_placeholders'] = df[text_column_name].apply(apply_placeholders)
    display(df[['Text', 'text_with_placeholders']].head())
else:
    print(f"Column '{text_column_name}' not found in the DataFrame.")

"""**Reasoning**:
The DataFrame `df` was not found in the current environment. I need to re-run the code that loads the data into `df` before applying the placeholder function. The cell `MAA2VRshy2jk` contains the code to load and process the data into a DataFrame named `df`.


"""

# Re-running the data loading and initial processing from cell MAA2VRshy2jk
# import necessary libraries if not already imported in this session
import pandas as pd
import json
import os
import re
from collections import Counter
from itertools import tee

# Define input and output paths directly
input_file = "./HateSpeechAllGender - Sheet3.csv"
outdir = "."
topk = 300

os.makedirs(outdir, exist_ok=True)

# Load CSV robustly
df = None
last_err = None
for enc in ["utf-8", "utf-8-sig", "iso-8859-1"]:
    try:
        df = pd.read_csv(input_file, encoding=enc)
        break
    except Exception as e:
        last_err = e
if df is None:
    raise RuntimeError(f"Could not read CSV. Last error: {last_err}")

# Clean
df = df.dropna(axis=1, how="all")
text_col = "Text" # Based on the README output in cell 4dc5cc56
df["_text_norm"] = df[text_col].map(normalize_text)

# Apply the placeholder function to the text column
if text_col in df.columns:
    df['text_with_placeholders'] = df[text_col].apply(apply_placeholders)
    display(df[[text_col, 'text_with_placeholders']].head())
else:
    print(f"Column '{text_col}' not found in the DataFrame.")

"""**Reasoning**:
The traceback indicates a `KeyError: 'Text'`, meaning the column named 'Text' was not found in the DataFrame `df`. Although the README indicated 'Text' as the column, the actual column name in the loaded DataFrame might be different. I need to inspect the DataFrame's columns to identify the correct text column before proceeding.


"""

print(df.columns)

"""**Reasoning**:
The output from the previous command shows that the text column is named ' Text' (with a leading space). I need to use this correct column name to apply the placeholder function and create the new column.


"""

# Apply the placeholder function to the text column using the correct column name
text_column_name = ' Text' # Corrected column name with leading space

if text_column_name in df.columns:
    df['text_with_placeholders'] = df[text_column_name].apply(apply_placeholders)
    display(df[[text_column_name, 'text_with_placeholders']].head())
else:
    print(f"Column '{text_column_name}' not found in the DataFrame.")

"""## Review results

### Subtask:
Display a sample of the original text and the text with placeholders to verify the transformation.

**Reasoning**:
Display the head of the DataFrame to show the original text and the text with placeholders, then display a few random rows to further verify the transformation.
"""

import pandas as pd

# Display the head of the DataFrame
print("Head of the DataFrame:")
display(df[[' Text', 'text_with_placeholders']].head())

# Display a few random rows
print("\nRandom rows from the DataFrame:")
display(df[[' Text', 'text_with_placeholders']].sample(5))

"""## Summary:

### Data Analysis Key Findings

*   The `apply_placeholders` function was successfully defined to replace sexual/adult terms using a lexicon and regex patterns.
*   The text column in the DataFrame was identified as ' Text' (with a leading space).
*   The `apply_placeholders` function was successfully applied to the ' Text' column of the DataFrame, creating a new column named `text_with_placeholders`.
*   The placeholder application process correctly replaced identified patterns and potentially words matching lexicon/regex rules with placeholders like `{NUMBER}` and `{LATIN_WORD}`.

### Insights or Next Steps

*   The placeholder application process appears to be working as intended, replacing sensitive or irrelevant terms with standardized placeholders.
*   Further analysis can now proceed using the `text_with_placeholders` column, which provides a more anonymized and potentially cleaner version of the text data for downstream tasks.

"""