# -*- coding: utf-8 -*-
"""GoT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLOG1yCm9GM8pALdVKxb5kynGhP4J7eX
"""

!pip install openai matplotlib networkx

import openai
import textwrap
import re
import random

client = openai.OpenAI(api_key="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")  # <-- Replace!

BRANCHES_PER_GEN = 6         # Population size per generation (higher: more diversity)
GENERATIONS = 4              # Number of evolutionary "generations"
ELITE_RATIO = 0.5            # Fraction of top nodes selected as parents
MUTATION_RATE = 0.25         # Chance of mutation (LLM is told to add something new)

EVAL_METRICS = [
    "Empathy Induction", "Cognitive Reframing", "Norm Activation",
    "Psychological Safety", "Legal Validity", "Linguistic Clarity",
    "Toxicity Shift", "Short Story or Analogy"
]

def create_initial_prompts_tamil(hate_input):
    # Returns a themed prompt list: (Law, Empathy, Educate)
    return [
        f"""பின்வரும் துவேஷ உரைக்கு சட்ட மற்றும் உரிமையை வலியுறுத்தும் அமைதியான counter speech பதிலை எழுதவும்.\n\nதுவேஷ உரை:\n\"\"\"{hate_input}\"\"\"\n""",
        f"""பின்வரும் துவேஷ உரைக்கு உணர்ச்சி மற்றும் மனிதநேயத்தில் வலுவான அமைதியான counter speech பதிலை எழுதவும்.\n\nதுவேஷ உரை:\n\"\"\"{hate_input}\"\"\"\n""",
        f"""பின்வரும் துவேஷ உரைக்கு கல்வி, விழிப்புணர்வு, மற்றும் நியாயத்தைக் கொண்டு எழுதப்பட்ட counter speech பதிலை உருவாக்கவும்.\n\nதுவேஷ உரை:\n\"\"\"{hate_input}\"\"\"\n"""
    ]

def create_crossover_prompt_tamil(parent_texts, mutation=False):
    bullet = "\n".join([f"{i+1}. {textwrap.shorten(t, width=120)}" for i, t in enumerate(parent_texts)])
    if mutation:
        mutate_str = "ஒரு புதுமையான legal example, உணர்ச்சி பழமொழி, அல்லது தனித்த கதை புதியதாக சேர்க்கவும்."
    else:
        mutate_str = ""
    return f"""மேலுள்ள counter speech பதில்களில் உள்ள சிறந்த அம்சங்களை (சட்டம், உணர்ச்சி, கல்வி கதைகள், நுண்ணுணர்ச்சி, analogy) ஒன்றாக இணைத்து புதிய சக்திவாய்ந்த பதிலை எழுதவும். {mutate_str}\n{bullet}"""

def create_evaluation_prompt(candidate_text):
    metrics_text = "\n".join(f"- {m}" for m in EVAL_METRICS)
    return f"""பின்வரும் counter speech உரையை கீழ்காணும் அளவுகோல்களில் 1 முதல் 5 வரை மதிப்பிடவும் (5 = சிறந்தது):

{metrics_text}

வடிவமைப்பு:
{'; '.join(f'{m}: X' for m in EVAL_METRICS)}

Counter Speech உரை:
\"\"\"{candidate_text.strip()}\"\"\"
"""

def generate_counter_speech(prompt, n=1):
    messages = [
        {"role": "system",
         "content": "நீங்கள் நீதிமன்றம், மனநயமும், கல்வியும் நிறைந்த தமிழ் counter speech generator. சிறந்த உரையையும் இனிமையான கதைகளையும் உருவாக்கவும்."},
        {"role": "user", "content": prompt}
    ]
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=messages,
        n=n,
        max_tokens=512,
        temperature=0.7
    )
    return [choice.message.content.strip() for choice in response.choices]

def evaluate_gpt(candidate_text):
    prompt = create_evaluation_prompt(candidate_text)
    messages = [
        {"role": "system", "content": "பதிலை பல அம்சங்களில் 1-5 அளவில் மதிப்பீடு செய்யவும்."},
        {"role": "user", "content": prompt}
    ]
    response = client.chat.completions.create(
        model="gpt-4o", messages=messages, max_tokens=128, temperature=0.3)
    scores = {}
    text = response.choices[0].message.content
    for m in EVAL_METRICS:
        m_pattern = re.search(f"{re.escape(m)}[:：] *([1-5])", text)
        if m_pattern:
            scores[m] = int(m_pattern.group(1))
    avg = sum(scores.values()) / len(scores) if scores else 0
    return scores, avg

if __name__ == "__main__":
    hate_speech_input = "பெண்கள் வீட்டில் இருந்தால்தான் நல்லது. வேலைக்கு வெளியே போனால் அணைத்தவர்களும் குறை சொல்வதுதான்."

    # Step 1: Initial Population (1 node for law, 1 for empathy, 1 for educate, rest random variations)
    prompts = create_initial_prompts_tamil(hate_speech_input)
    pop = []
    for prompt in prompts:
        pop.append({"text": generate_counter_speech(prompt, n=1)[0], "parents": ["INIT"], "generation": 1})

    # Fill up population with random variations too
    while len(pop) < BRANCHES_PER_GEN:
        prompt = random.choice(prompts)
        pop.append({"text": generate_counter_speech(prompt, n=1)[0], "parents": ["INIT"], "generation": 1})

    print("\n=== துவக்கத் தொகுதி (Generation 1, Population) ===")
    for idx, node in enumerate(pop, 1):
        print(f"[Gen 1, Node {idx}]:")
        print(textwrap.fill(node['text'], 80))
        print("="*80)

    # Main GA Loop
    for gen in range(2, GENERATIONS + 1):
        print(f"\n===={gen}வது தலைமுறை (Generation {gen})====")
        # Evaluate all current population
        for idx, c in enumerate(pop, 1):
            scores, avg = evaluate_gpt(c['text'])
            c['score'] = avg
            c['scores'] = scores
            print(f"[Gen {c['generation']}, Node {idx}]: {textwrap.shorten(c['text'], width=120)}\n"
                  f"Score: {avg:.2f}, Subscores: {scores}")
        # Selection
        pop.sort(key=lambda x: -x['score'])
        num_elite = max(2, int(ELITE_RATIO * BRANCHES_PER_GEN))
        parents = pop[:num_elite]
        print(f"\n--Selection (Top {num_elite})--")
        for i, n in enumerate(parents, 1):
            print(f"{i}. {textwrap.shorten(n['text'], width=100)} | Score: {n['score']:.2f}")
        # Crossover and mutation for next generation
        new_pop = []
        parent_indices = [i for i in range(len(parents))]
        while len(new_pop) < BRANCHES_PER_GEN:
            inds = random.sample(parent_indices, 2 if random.random() > 0.35 else 3)
            parent_texts = [parents[i]['text'] for i in inds]
            mutation = (random.random() < MUTATION_RATE)
            prompt = create_crossover_prompt_tamil(parent_texts, mutation)
            child_text = generate_counter_speech(prompt, n=1)[0]
            new_pop.append({
                "text": child_text,
                "parents": inds,
                "mutation": mutation,
                "generation": gen
            })
            print(f"\nGenerated Node (Gen {gen}, Parent(s) {inds}){' [Mutated]' if mutation else ''}:\n" +
                  textwrap.fill(child_text, 80))
            print("-"*60)
        pop = new_pop

    # Final eval and print
    for idx, c in enumerate(pop, 1):
        scores, avg = evaluate_gpt(c['text'])
        c['score'] = avg
        c['scores'] = scores
        print(f"\n[FINAL Gen Node {idx}] (Parents: {c['parents']} {'Mutated' if c.get('mutation') else ''})")
        print(f"Score: {avg:.2f}, Subscores: {scores}")
        print(textwrap.fill(c['text'], 100))
        print("="*80)

    # Display best results
    pop.sort(key=lambda x: -x['score'])
    print(f"\n=== Genetic GoT Final Best Counter-Speeches (Top 3 by Score) ===")
    for idx, node in enumerate(pop[:3], 1):
        print(f"\n[{idx}] (Score {node['score']:.2f}) | Parents: {node['parents']} {'[Mutated]' if node.get('mutation') else ''}\n")
        print(textwrap.fill(node['text'], 120))
        print("="*100)

import openai
import textwrap
import re
import random

client = openai.OpenAI(api_key="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")  # Replace with your key

BRANCHES_PER_GEN = 6         # Population size per generation (try 6-12)
GENERATIONS = 3              # Number of evolutionary "generations" (depth)
ELITE_RATIO = 0.5            # Top% survive to next generation
MUTATION_RATE = 0.25         # Chance to inject additional creative prompt

EVAL_METRICS = [
    "Empathy Induction", "Cognitive Reframing", "Norm Activation",
    "Psychological Safety", "Legal Validity", "Linguistic Clarity",
    "Toxicity Shift", "Short Story or Analogy"
]

def create_initial_prompt_tamil(hate):
    return f"""
பின்வரும் துவேஷ உரைக்கு எதிராக 3 வேறு வகையான counter speech பதில்களை உருவாக்கவும்: story, empathy, சட்டம்.

துவேஷ உரை:
\"""{hate.strip()}\""\"
"""

def create_crossover_prompt_tamil(parent1, parent2, with_mutation=False):
    prompt = f"""
இரு counter speech பதில்களில் உள்ள சிறந்த அம்சங்களை (உணர்ச்சி, கதையுடன் சட்டம்/ஒழுங்கு/analogy) ஒன்றாக சேர்த்து ஒரு புதிய பதிலை உருவாக்கவும்.

1. {parent1}
2. {parent2}
"""
    if with_mutation:
        prompt += "\nஏதேனும் புதிய உவமையும், அல்லது புதுமையான சட்டம்/உணர்ச்சி வார்த்தையும் சேர்க்கவும்."
    return prompt

def create_evaluation_prompt(candidate_text):
    metrics_text = "\n".join(f"- {m}" for m in EVAL_METRICS)
    return f"""
பின்வரும் counter speech உரையை கீழ்காணும் அளவுகோல்களில் 1 முதல் 5 வரை மதிப்பிடவும் (5 = சிறந்தது):

{metrics_text}

வடிவமைப்பு:
{'; '.join(f'{m}: X' for m in EVAL_METRICS)}

Counter Speech உரை:
\"""{candidate_text.strip()}\""\"
"""

def generate_counter_speech(prompt, n=3):
    messages = [
        {
            "role": "system",
            "content": "நீங்கள் ஒரு சக்திவாய்ந்த, அமைதியான, ஆன்மிக/சமூக நுண்ணுணர்சி கொண்ட counter speech generator. சட்டம், உணர்ச்சி, கதைகள் சேர்க்கவும்."
        },
        {"role": "user", "content": prompt}
    ]
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=messages,
        n=n,
        max_tokens=512,
        temperature=0.7
    )
    return [choice.message.content.strip() for choice in response.choices]

def evaluate_gpt(candidate_text):
    prompt = create_evaluation_prompt(candidate_text)
    messages = [
        {
            "role": "system",
            "content": "பதிலை பல அம்சங்களில் 1-5 அளவில் மதிப்பீடு செய்யவும்."
        },
        {"role": "user", "content": prompt}
    ]
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=messages,
        max_tokens=128,
        temperature=0.3
    )
    scores = {}
    text = response.choices[0].message.content
    for m in EVAL_METRICS:
        m_pattern = re.search(f"{re.escape(m)}[:：] *([1-5])", text)
        if m_pattern:
            scores[m] = int(m_pattern.group(1))
    avg = sum(scores.values()) / len(scores) if scores else 0
    return scores, avg

if __name__ == "__main__":
    hate_speech_input = "பெண்கள் வீட்டில் இருந்தால்தான் நல்லது. வேலைக்கு வெளியே போனால் அணைத்தவர்களும் குறை சொல்வதுதான்."

    # Step 1: Generate initial population
    initial_prompt = create_initial_prompt_tamil(hate_speech_input)
    population = generate_counter_speech(initial_prompt, n=BRANCHES_PER_GEN)
    nodes = [{"text": t, "generation": 1} for t in population]

    print("\n=== Generation 1: Initial Candidates ===")
    for idx, node in enumerate(nodes, 1):
        print(f"[Gen 1, Candidate {idx}]:")
        print(textwrap.fill(node['text'], 80))
        print("-" * 80)

    for gen in range(2, GENERATIONS + 1):
        # Evaluate fitness of all nodes
        for idx, c in enumerate(nodes, 1):
            scores, avg_score = evaluate_gpt(c['text'])
            c['score'] = avg_score
            print(f"\n[Gen {c['generation']}, Candidate {idx}] Evaluation Scores:\n{scores}\nAverage: {avg_score:.2f}")
            print("-" * 80)

        # Selection: keep top ELITE_RATIO fraction
        nodes.sort(key=lambda x: -x['score'])
        num_elite = max(2, int(ELITE_RATIO * BRANCHES_PER_GEN))
        selected = nodes[:num_elite]

        print(f"\n=== Generation {gen}: Selected Top {num_elite} Candidates for Crossover ===")
        for idx, node in enumerate(selected, 1):
            print(f"[Gen {gen-1}, Candidate {idx}]: Score = {node['score']:.2f}")
            print(textwrap.fill(node['text'], 80))
            print("=" * 80)

        # Crossover & mutation: make next generation
        next_gen = []
        while len(next_gen) < BRANCHES_PER_GEN:
            p1, p2 = random.sample(selected, 2)
            mut = (random.random() < MUTATION_RATE)
            crossover_prompt = create_crossover_prompt_tamil(p1['text'], p2['text'], with_mutation=mut)
            offspring = generate_counter_speech(crossover_prompt, n=1)[0]
            next_gen.append({"text": offspring, "generation": gen})

            print(f"\n[Gen {gen}, New Candidate Generated by Merging Candidate {selected.index(p1)+1} and {selected.index(p2)+1}{' with Mutation' if mut else ''}]:")
            print(textwrap.fill(offspring, 80))
            print("-" * 80)

        nodes = next_gen

    # Final eval and display
    print("\n=== Final Generation Evaluation ===")
    for idx, c in enumerate(nodes, 1):
        scores, avg_score = evaluate_gpt(c['text'])
        c['score'] = avg_score
        print(f"\n[Final Gen, Candidate {idx}] Evaluation Scores:\n{scores}\nAverage: {avg_score:.2f}")
        print(textwrap.fill(c['text'], 80))
        print("=" * 80)

    nodes.sort(key=lambda x: -x['score'])

    print(f"\n=== Genetic GoT Final Best Counter Speeches (Top 3 by Rating) ===")
    for idx, node in enumerate(nodes[:3], 1):
        print(f"\n[{idx}] (Rating {node['score']:.2f}) — {textwrap.fill(node['text'], 100)}\n")

import openai
import re
import textwrap

# Replace with your OpenAI API key
client = openai.OpenAI(api_key="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")

BRANCHES_PER_STEP = 3
DEPTH = 3  # Change for deeper/wider exploration

PSYCHOLOGICAL_METRICS_TAMIL = [
    "Empathy Induction",
    "Cognitive Reframing",
    "Norm Activation",
    "Psychological Safety",
    "Legal Validity",
    "Linguistic Clarity",
    "Toxicity Shift",
    "Short Story or Analogy"
]

def create_tot_prompt_tamil(input_text: str) -> str:
    return f"""
பின்வரும் துவேஷ உரைக்கு எதிராக ஒரு அமைதியான, மரியாதையான, மற்றும் கல்விமிக்க counter speech பதிலை உருவாக்கவும்.

- பதில் calm, formal, educational, non-triggering, மற்றும் மனிதநேயம் நிறைந்ததாக இருக்க வேண்டும்.
- கருத்தை தெளிவாகத் தெரிவிக்க சிறிய கதை (short story) அல்லது உவமைகளை பாவிக்கவும்.
- சமுதாய/சட்ட நெறிகளை அவசியம் மேற்கோள் காட்டவும்.
- உரையாடல் அமைதிக்கும், உணர்ச்சி பாதுகாப்புக்கும் பாதிப்பில்லாமல் இருக்க வேண்டும்.

துவேஷ உரை:
\"""{input_text.strip()}\""\"
"""

def create_evaluation_prompt(candidate_text: str) -> str:
    metrics_text = "\n".join(f"- {m}" for m in PSYCHOLOGICAL_METRICS_TAMIL)
    return f"""
பின்வரும் counter speech உரையை இந்த அளவுகோல்களில் 1 முதல் 5 வரை மதிப்பிடவும் (5 = சிறந்தது):

{metrics_text}

வடிவமைப்பு:
{'; '.join(f'{m}: X' for m in PSYCHOLOGICAL_METRICS_TAMIL)}

Counter Speech உரை:
\"""{candidate_text.strip()}\""\"
"""

class ToTNode:
    def __init__(self, text, depth, parent_id=None):
        self.text = text
        self.depth = depth
        self.parent_id = parent_id
        self.node_id = id(self)
        self.children = []
        self.rating = None

def generate_counter_speech(prompt, n=BRANCHES_PER_STEP):
    messages = [
        {
            "role": "system",
            "content": "நீங்கள் ஒரு அமைதியான, மரியாதையான, கல்விமிக்க தமிழ் counter speech எழுத விரும்புகிறீர்கள். அமைதியான கதைகள், சட்ட தகவல் பயன்படுத்தவும்."
        },
        {"role": "user", "content": prompt}
    ]
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=messages,
        n=n,
        max_tokens=512,
        temperature=0.7
    )
    return [choice.message.content.strip() for choice in response.choices]

def evaluate_candidate_with_gpt(candidate_text):
    prompt = create_evaluation_prompt(candidate_text)
    messages = [
        {
            "role": "system",
            "content": "ஏற்கனவே உள்ள counter speech பதிலை கீழ்க்காணும் அளவுகோல்களில் மதிப்பிடுங்கள். பதில் வடிவம்: metric: X; ... X என்பது 1-5."
        },
        {"role": "user", "content": prompt}
    ]
    result = client.chat.completions.create(
        model="gpt-4o",
        messages=messages,
        max_tokens=128,
        temperature=0.3
    )
    scores = {}
    text = result.choices[0].message.content
    for m in PSYCHOLOGICAL_METRICS_TAMIL:
        m_pattern = re.search(f"{re.escape(m)}[:：] *([1-5])", text)
        if m_pattern:
            scores[m] = int(m_pattern.group(1))
    avg_rating = sum(scores.values()) / len(scores) if scores else 0
    return scores, avg_rating

def tot_traverse(seed, max_depth=DEPTH, branches=BRANCHES_PER_STEP, rating_threshold=3.2):
    all_nodes = []
    depth_to_nodes = {}
    root_texts = generate_counter_speech(create_tot_prompt_tamil(seed), n=branches)
    roots = []
    for txt in root_texts:
        n = ToTNode(txt, depth=1, parent_id=None)
        roots.append(n)
        all_nodes.append(n)
    current_level = roots
    depth_to_nodes[1] = current_level.copy()
    for depth in range(2, max_depth + 1):
        next_level = []
        for parent in current_level:
            parent.rating = evaluate_candidate_with_gpt(parent.text)[1]
            if parent.rating < rating_threshold:
                continue
            cs_children = generate_counter_speech(create_tot_prompt_tamil(parent.text), n=branches)
            for ctxt in cs_children:
                child = ToTNode(ctxt, depth=depth, parent_id=parent.node_id)
                all_nodes.append(child)
                parent.children.append(child)
                next_level.append(child)
        current_level = next_level
        depth_to_nodes[depth] = current_level.copy()
    for node in current_level:
        node.rating = evaluate_candidate_with_gpt(node.text)[1]
    return all_nodes, current_level, depth_to_nodes

if __name__ == "__main__":
    hate_speech_input = "சிங்கப்பூர் ஏன் போராங்கா??? எல்லாம் அடிவேலை பார்க்கத்தான்.குத்துக்கு ஆயிரம் ரூபாய் சார்ச்."
    DEPTH = 4  # Change for shallower/deeper runs

    all_nodes, final_nodes, depth_to_nodes = tot_traverse(
        hate_speech_input, max_depth=DEPTH, branches=BRANCHES_PER_STEP, rating_threshold=3.2
    )

    # Fallback display logic for final counter speeches if deepest level nodes are empty:
    to_display = final_nodes if final_nodes else next(
        (nodes for d, nodes in reversed(sorted(depth_to_nodes.items())) if nodes), []
    )
    print(f"\n=== Final Counter Speech Outputs (Depth {DEPTH if final_nodes else len(to_display)}) ===")
    for idx, node in enumerate(to_display, 1):
        print(f"\n[{idx}] (rating {node.rating:.2f}) — {textwrap.shorten(node.text, width=200)}\n")

