# -*- coding: utf-8 -*-
"""GPT4_tot_AllGender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKd3URnsom7hQX7G8GFj8_ggz9adK4zw
"""

import json
import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt

# Load dataset
with open("/content/drive/MyDrive/abusiveWomenDataset/July7.json", "r", encoding="utf-8") as f:
    dataset = json.load(f)

# Flatten output into DataFrame
records = []
for entry in dataset:
    output = entry["output"][0] if isinstance(entry["output"], list) else entry["output"]
    records.append({
        "input": entry["input"],
        "Class": output.get("Class", "").strip(),
        "Category": output.get("Category", "").strip(),
        "Subcategories": [s.strip() for s in output.get("Subcategories", "").split(",") if s.strip()],
        "Bias": output.get("Bias", "").strip(),
        "Target": output.get("Target", "").strip()
    })

df = pd.DataFrame(records)
print("✅ Total entries:", len(df))

# Show class distribution
print("\n📊 Class Distribution:")
print(df["Class"].value_counts())

# Subcategories distribution
subcategory_counts = Counter(sub for subs in df["Subcategories"] for sub in subs)
bias_counts = df["Bias"].value_counts()
target_counts = df["Target"].value_counts()

# Pie chart: Hate vs Non-Hate
df["Class"].value_counts().plot.pie(autopct='%1.1f%%', startangle=90, title="Class Distribution", ylabel="")
plt.show()

# Bar chart: Subcategories
plt.figure(figsize=(10, 5))
plt.bar(subcategory_counts.keys(), subcategory_counts.values())
plt.xticks(rotation=45)
plt.title("Subcategory Distribution")
plt.ylabel("Frequency")
plt.show()

# Bar chart: Bias
bias_counts.plot.bar(title="Bias Distribution", ylabel="Count")
plt.xticks(rotation=45)
plt.show()

# Bar chart: Target
target_counts.plot.bar(title="Target Distribution", ylabel="Count", color="orange")
plt.xticks(rotation=0)
plt.show()

# ✅ FULL JUPYTER NOTEBOOK CODE: Tree-of-Thought Hate Speech Analyzer (All Genders)
# --------------------------------------------------------------
# - Uses GPT-4 with OpenAI v1 client
# - Reasoning steps (Tree-of-Thought)
# - Traversable tree structure
# - Final JSON output + Tamil Counter Speech + Subcategory Severity Ranking
# - Uses dataset-based instruction inside ToT prompt
# --------------------------------------------------------------

from openai import OpenAI
import json

# 🔐 Initialize OpenAI client
client = OpenAI(api_key="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")  # Replace with your actual OpenAI key

# === Load Dataset ===
with open("/content/drive/MyDrive/abusiveWomenDataset/July7.json", "r", encoding="utf-8") as f:
    dataset = json.load(f)

instruction = dataset[0]["instruction"]

# === Extract Allowed Labels ===
subcategories_set = set()
bias_set = set()
target_set = set()

for entry in dataset:
    output = entry["output"][0] if isinstance(entry["output"], list) else entry["output"]
    subcategories_set.update(map(str.strip, output.get("Subcategories", "").split(',')))
    bias_set.add(output.get("Bias", "").strip())
    target_set.add(output.get("Target", "").strip())

allowed_subcategories = sorted([s for s in subcategories_set if s])
allowed_biases = sorted([b for b in bias_set if b])
allowed_targets = sorted([t for t in target_set if t])


# === Tree-of-Thought Node Class ===
class ToTNode:
    def __init__(self, question, parent=None):
        self.question = question
        self.answer = None
        self.parent = parent
        self.children = []

    def add_child(self, question):
        child = ToTNode(question, parent=self)
        self.children.append(child)
        return child

    def delete_child(self, index):
        if 0 <= index < len(self.children):
            del self.children[index]

    def traverse(self, level=0):
        indent = "  " * level
        print(f"{indent}- Q: {self.question}")
        if self.answer:
            print(f"{indent}  A: {self.answer}")
        for child in self.children:
            child.traverse(level + 1)


# === GPT Reasoning Step ===
def gpt_reason(prompt):
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.4,
        max_tokens=300
    )
    return response.choices[0].message.content.strip()


# === Build the Reasoning Tree ===
def build_tot_tree(user_input):
    root = ToTNode(
    f"கீழே ஒரு தமிழ் உரை மற்றும் அது தொடர்பான பன்முக கேள்விகள் உள்ளன. கீழே உள்ள வழிமுறையின் அடிப்படையில் பதில் அளிக்கவும்.\n\n"
    f"### வழிமுறை (Instruction):\n{instruction}\n\n"
    f"### உரை (Input):\n{user_input}\n"
    )

    root.add_child("படி 1: இலக்குக் குழு யார்? Women, Men, LGBTQ+, Organization, அல்லது Others என்பதிலிருந்து தேர்ந்தெடுக்கவும்.")
    root.add_child("படி 2: இந்த உரையில் வெறுப்புப் பேச்சு உள்ளதா? ஏன்?")
    root.add_child("படி 3: Explicit அல்லது Implicit? விளக்கவும்.")
    root.add_child(f"படி 4: பொருத்தமான துணைப் பிரிவுகளை மட்டும் கீழே உள்ள பட்டியலிலிருந்து தேர்வு செய்யவும். JSON format-இல் பதிலளிக்கவும்: {json.dumps(allowed_subcategories)}")
    root.add_child(f"படி 5: படி 4ல் தேர்வு செய்யப்பட்ட ஒவ்வொரு துணைப் பிரிவுக்கும் தீவிரத்தன்மையை Low, Mild, High, Severe என வகைப்படுத்தவும். JSON வடிவில் பதிலளிக்கவும்.")
    root.add_child(f"படி 6: பாகுபாடு உள்ளதா? இருப்பின் {', '.join(allowed_biases)} என்பதிலிருந்து தேர்வு செய்யவும் மற்றும் விளக்கவும்.")
    root.add_child(f"படி 7: இலக்கு ஒரு தனிநபரா அல்லது குழுவா? கீழ்காணும் ஒன்றிலிருந்து தேர்வு செய்யவும்: {', '.join(allowed_targets)}.")
    return root


# === Fill the Reasoning Tree ===
def run_tot_analysis(root):
    for child in root.children:
        prompt = f"{root.question}\n\n{child.question}"
        child.answer = gpt_reason(prompt)


# === Extract Final Result ===
def generate_output_from_tree(root):
    try:
        try:
            subcats = json.loads(root.children[3].answer.strip())
            subcats = [s for s in subcats if s in allowed_subcategories]
        except:
            subcats = []

        try:
            severity_map = json.loads(root.children[4].answer.strip())
            severity = {k: v for k, v in severity_map.items() if k in subcats}
        except:
            severity = {}

        result = {
            "Target_Group": next((g for g in ["Women", "Men", "LGBTQ+", "Organization", "Others"] if g.lower() in root.children[0].answer.lower()), "Others"),
            "Class": "Hate" if "yes" in root.children[1].answer.lower() else "Non-Hate",
            "Category": "Explicit" if "explicit" in root.children[2].answer.lower() else "Implicit",
            "Subcategories": subcats,
            "Subcategory_Severity": severity,
            "Bias": next((b for b in allowed_biases if b.lower() in root.children[5].answer.lower()), "No Bias"),
            "Target": next((t for t in allowed_targets if t.lower() in root.children[6].answer.lower()), "individual")
        }
    except Exception as e:
        result = {"error": f"Failed to extract from reasoning tree: {e}"}
    return result


# === Generate Counter Speech in Tamil ===
def generate_counter_speech(text, category, target_group):
    if category == "Explicit":
        prompt = (
            f"வெறுப்புப் பேச்சு: \"{text}\"\n\n"
            f"இந்த உரைக்கு சட்ட ரீதியான (IPC பிரிவுகள்) மற்றும் மரியாதையான தமிழில் எதிர்வினை (counter speech) எழுதவும்."
            f" இலக்குக் குழு: {target_group}"
        )
    else:
        prompt = (
            f"வெறுப்புப் பேச்சு: \"{text}\"\n\n"
            f"இந்த உரைக்கு எதிராக தமிழ் மொழியில் ஒரு உணர்வுபூர்வமான, மரியாதையுடனான, சமத்துவத்தை வலியுறுத்தும் பதிலை (counter speech) எழுதவும்."
            f" இலக்குக் குழு: {target_group}"
        )
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.5,
        max_tokens=256
    )
    return response.choices[0].message.content.strip()


# === Evaluation Metrics ===
def evaluate_prediction(pred, gold):
    return {
        "Match": pred.get("Class") == gold.get("Class"),
        "Predicted": pred.get("Class"),
        "Expected": gold.get("Class")
    }

# === MAIN EXECUTION ===
def analyze_with_tot(user_input):
    tree = build_tot_tree(user_input)
    run_tot_analysis(tree)
    result = generate_output_from_tree(tree)

    if result.get("Class") == "Hate":
        counter = generate_counter_speech(user_input, result["Category"], result["Target_Group"])
        result["Counter_Speech"] = counter

    if result.get("Class") == "Hate":
        counter = generate_counter_speech(user_input, result["Category"], result["Target_Group"])
        result["Counter_Speech"] = counter

    print(json.dumps(result, ensure_ascii=False, indent=2))
    return tree, result


# === Run ===
user_input = input("📥 Enter a Tamil sentence to analyze with ToT: ")
tree, result = analyze_with_tot(user_input)

# ✅ FULL JUPYTER NOTEBOOK CODE: Tree-of-Thought Hate Speech Analyzer (All Genders)
# --------------------------------------------------------------
# - Uses GPT-4 with OpenAI v1 client
# - Reasoning steps (Tree-of-Thought)
# - Traversable tree structure
# - Final JSON output + Tamil Counter Speech + Subcategory Severity Ranking
# - Uses dataset-based instruction inside ToT prompt
# --------------------------------------------------------------

from openai import OpenAI
import json

# 🔐 Initialize OpenAI client
client = OpenAI(api_key="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")
# === Load Dataset ===
with open("/content/drive/MyDrive/abusiveWomenDataset/July7.json", "r", encoding="utf-8") as f:
    dataset = json.load(f)

instruction = dataset[0]["instruction"]

# === Extract Allowed Labels ===
subcategories_set = set()
bias_set = set()
target_set = set()

for entry in dataset:
    output = entry["output"][0] if isinstance(entry["output"], list) else entry["output"]
    subcategories_set.update(map(str.strip, output.get("Subcategories", "").split(',')))
    bias_set.add(output.get("Bias", "").strip())
    target_set.add(output.get("Target", "").strip())

allowed_subcategories = sorted([s for s in subcategories_set if s])
allowed_biases = sorted([b for b in bias_set if b])
allowed_targets = sorted([t for t in target_set if t])


# === Tree-of-Thought Node Class ===
class ToTNode:
    def __init__(self, question, parent=None):
        self.question = question
        self.answer = None
        self.parent = parent
        self.children = []

    def add_child(self, question):
        child = ToTNode(question, parent=self)
        self.children.append(child)
        return child

    def delete_child(self, index):
        if 0 <= index < len(self.children):
            del self.children[index]

    def traverse(self, level=0):
        indent = "  " * level
        print(f"{indent}- Q: {self.question}")
        if self.answer:
            print(f"{indent}  A: {self.answer}")
        for child in self.children:
            child.traverse(level + 1)


# === GPT Reasoning Step ===
def gpt_reason(prompt):
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.4,
        max_tokens=300
    )
    return response.choices[0].message.content.strip()


# === Build the Reasoning Tree ===
def build_tot_tree(user_input):
    root = ToTNode(
        f"கீழே ஒரு தமிழ் உரை மற்றும் அது தொடர்பான பன்முக கேள்விகள் உள்ளன. கீழே உள்ள வழிமுறையின் அடிப்படையில் பதில் அளிக்கவும்.\n\n"
        f"### வழிமுறை (Instruction):\n{instruction}\n\n"
        f"### உரை (Input):\n{user_input}\n"
    )
    root.add_child("படி 1: இலக்குக் குழு யார்? Women, Men, LGBTQ+, Organization, அல்லது Others என்பதிலிருந்து தேர்ந்தெடுக்கவும்.")
    root.add_child("படி 2: இந்த உரையில் வெறுப்புப் பேச்சு உள்ளதா? ஏன்?")
    root.add_child("படி 3: Explicit அல்லது Implicit? விளக்கவும்.")
    root.add_child(f"படி 4: பொருத்தமான துணைப் பிரிவுகளை மட்டும் கீழே உள்ள பட்டியலிலிருந்து தேர்வு செய்யவும். JSON format-இல் பதிலளிக்கவும்: {json.dumps(allowed_subcategories)}")
    root.add_child(f"படி 5: படி 4ல் தேர்வு செய்யப்பட்ட ஒவ்வொரு துணைப் பிரிவுக்கும் தீவிரத்தன்மையை Low, Mild, High, Severe என வகைப்படுத்தவும். JSON வடிவில் பதிலளிக்கவும்.")
    root.add_child(f"படி 6: பாகுபாடு உள்ளதா? இருப்பின் {', '.join(allowed_biases)} என்பதிலிருந்து தேர்வு செய்யவும் மற்றும் விளக்கவும்.")
    root.add_child(f"படி 7: இலக்கு ஒரு தனிநபரா அல்லது குழுவா? கீழ்காணும் ஒன்றிலிருந்து தேர்வு செய்யவும்: {', '.join(allowed_targets)}.")
    return root


# === Fill the Reasoning Tree ===
def run_tot_analysis(root):
    for child in root.children:
        prompt = f"{root.question}\n\n{child.question}"
        child.answer = gpt_reason(prompt)


# === Extract Final Result ===
def generate_output_from_tree(root):
    try:
        try:
            subcats = json.loads(root.children[3].answer.strip())
            subcats = [s for s in subcats if s in allowed_subcategories]
        except:
            subcats = []

        try:
            severity_map = json.loads(root.children[4].answer.strip())
            severity = {k: v for k, v in severity_map.items() if k in subcats}
        except:
            severity = {}

        result = {
            "Target_Group": next((g for g in ["Women", "Men", "LGBTQ+", "Organization", "Others"] if g.lower() in root.children[0].answer.lower()), "Others"),
            "Class": "Hate" if "yes" in root.children[1].answer.lower() else "Non-Hate",
            "Category": "Explicit" if "explicit" in root.children[2].answer.lower() else "Implicit",
            "Subcategories": subcats,
            "Subcategory_Severity": severity,
            "Bias": next((b for b in allowed_biases if b.lower() in root.children[5].answer.lower()), "No Bias"),
            "Target": next((t for t in allowed_targets if t.lower() in root.children[6].answer.lower()), "individual")
        }
    except Exception as e:
        result = {"error": f"Failed to extract from reasoning tree: {e}"}
    return result


# === Generate Counter Speech in Tamil ===
def generate_counter_speech(text, category, target_group):
    if category == "Explicit":
        prompt = (
            f"வெறுப்புப் பேச்சு: \"{text}\"\n\n"
            f"இந்த உரைக்கு சட்ட ரீதியான (IPC பிரிவுகள்) மற்றும் மரியாதையான தமிழில் எதிர்வினை (counter speech) எழுதவும்."
            f" இலக்குக் குழு: {target_group}"
        )
    else:
        prompt = (
            f"வெறுப்புப் பேச்சு: \"{text}\"\n\n"
            f"இந்த உரைக்கு எதிராக தமிழ் மொழியில் ஒரு உணர்வுபூர்வமான, மரியாதையுடனான, சமத்துவத்தை வலியுறுத்தும் பதிலை (counter speech) எழுதவும்."
            f" இலக்குக் குழு: {target_group}"
        )
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.5,
        max_tokens=256
    )
    return response.choices[0].message.content.strip()


# === Evaluation Metrics ===
def evaluate_prediction(pred, gold):
    return {
        "Match": pred.get("Class") == gold.get("Class"),
        "Predicted": pred.get("Class"),
        "Expected": gold.get("Class")
    }

# === MAIN EXECUTION ===
def analyze_with_tot(user_input):
    tree = build_tot_tree(user_input)
    run_tot_analysis(tree)
    result = generate_output_from_tree(tree)

    if result.get("Class") == "Hate":
        counter = generate_counter_speech(user_input, result["Category"], result["Target_Group"])
        result["Counter_Speech"] = counter

    if result.get("Class") == "Hate":
        counter = generate_counter_speech(user_input, result["Category"], result["Target_Group"])
        result["Counter_Speech"] = counter

    print(json.dumps(result, ensure_ascii=False, indent=2))
    return tree, result


# === Run & Evaluate ===
user_input = input("📥 Enter a Tamil sentence to analyze with ToT: ")
tree, result = analyze_with_tot(user_input)

# Optional: Compare against gold label if available
for entry in dataset:
    if entry["input"].strip() == user_input.strip():
        gold = entry["output"][0] if isinstance(entry["output"], list) else entry["output"]
        evaluation = evaluate_prediction(result, gold)
        print("📊 Evaluation:")
        print(json.dumps(evaluation, ensure_ascii=False, indent=2))
        break

# ✅ FULL JUPYTER NOTEBOOK CODE: Tree-of-Thought Hate Speech Analyzer (All Genders)
# --------------------------------------------------------------
# - Uses GPT-4 with OpenAI v1 client
# - Reasoning steps (Tree-of-Thought)
# - Traversable tree structure
# - Final JSON output + Tamil Counter Speech + Subcategory Severity Ranking
# - Uses dataset-based instruction inside ToT prompt
# --------------------------------------------------------------

from openai import OpenAI
import json

# 🔐 Initialize OpenAI client
client = OpenAI(api_key="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")  # Replace with your actual OpenAI key

# === Load Dataset ===
with open("/content/drive/MyDrive/abusiveWomenDataset/July7.json", "r", encoding="utf-8") as f:
    dataset = json.load(f)

instruction = dataset[0]["instruction"]

# === Extract Allowed Labels ===
subcategories_set = set()
bias_set = set()
target_set = set()

for entry in dataset:
    output = entry["output"][0] if isinstance(entry["output"], list) else entry["output"]
    subcategories_set.update(map(str.strip, output.get("Subcategories", "").split(',')))
    bias_set.add(output.get("Bias", "").strip())
    target_set.add(output.get("Target", "").strip())

allowed_subcategories = sorted([s for s in subcategories_set if s])
allowed_biases = sorted([b for b in bias_set if b])
allowed_targets = sorted([t for t in target_set if t])


# === Tree-of-Thought Node Class ===
class ToTNode:
    def __init__(self, question, parent=None):
        self.question = question
        self.answer = None
        self.parent = parent
        self.children = []

    def add_child(self, question):
        child = ToTNode(question, parent=self)
        self.children.append(child)
        return child

    def delete_child(self, index):
        if 0 <= index < len(self.children):
            del self.children[index]

    def traverse(self, level=0):
        indent = "  " * level
        print(f"{indent}- Q: {self.question}")
        if self.answer:
            print(f"{indent}  A: {self.answer}")
        for child in self.children:
            child.traverse(level + 1)


# === GPT Reasoning Step ===
def gpt_reason(prompt):
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.4,
        max_tokens=300
    )
    return response.choices[0].message.content.strip()



# === Build the Reasoning Tree ===
def build_tot_tree(user_input):
    root = ToTNode(
        f"கீழே ஒரு தமிழ் உரை மற்றும் அது தொடர்பான பன்முக கேள்விகள் உள்ளன. கீழே உள்ள வழிமுறையின் அடிப்படையில் பதில் அளிக்கவும்.\n\n"
        f"### வழிமுறை (Instruction):\n{instruction}\n\n"
        f"### உரை (Input):\n{user_input}\n"
    )
    root.add_child("படி 1: இலக்குக் குழு யார்? Women, Men, LGBTQ+, Organization, அல்லது Others என்பதிலிருந்து தேர்ந்தெடுக்கவும்.")
    root.add_child("படி 2: இந்த உரையில் வெறுப்புப் பேச்சு உள்ளதா? ஏன்?")
    root.add_child("படி 3: Explicit அல்லது Implicit? விளக்கவும்.")
    root.add_child(f"படி 4: பொருத்தமான துணைப் பிரிவுகளை மட்டும் கீழே உள்ள பட்டியலிலிருந்து தேர்வு செய்யவும். JSON format-இல் பதிலளிக்கவும்: {json.dumps(allowed_subcategories)}")
    root.add_child(f"படி 5: படி 4ல் தேர்வு செய்யப்பட்ட ஒவ்வொரு துணைப் பிரிவுக்கும் தீவிரத்தன்மையை Low, Mild, High, Severe என வகைப்படுத்தவும். JSON வடிவில் பதிலளிக்கவும்.")
    root.add_child(f"படி 6: பாகுபாடு உள்ளதா? இருப்பின் {', '.join(allowed_biases)} என்பதிலிருந்து தேர்வு செய்யவும் மற்றும் விளக்கவும்.")
    root.add_child(f"படி 7: இலக்கு ஒரு தனிநபரா அல்லது குழுவா? கீழ்காணும் ஒன்றிலிருந்து தேர்வு செய்யவும்: {', '.join(allowed_targets)}.")
    return root

# === Fill the Reasoning Tree ===
def run_tot_analysis(root):
    for child in root.children:
        prompt = f"{root.question}\n\n{child.question}"
        child.answer = gpt_reason(prompt)


# === Extract Final Result ===
def generate_output_from_tree(root):
    try:
        try:
            subcats = json.loads(root.children[3].answer.strip())
            subcats = [s for s in subcats if s in allowed_subcategories]
        except:
            subcats = []

        try:
            severity_map = json.loads(root.children[4].answer.strip())
            severity = {k: v for k, v in severity_map.items() if k in subcats}
        except:
            severity = {}

        result = {
            "Target_Group": next((g for g in ["Women", "Men", "LGBTQ+", "Organization", "Others"] if g.lower() in root.children[0].answer.lower()), "Others"),
            "Class": "Hate" if "yes" in root.children[1].answer.lower() else "Non-Hate",
            "Category": "Explicit" if "explicit" in root.children[2].answer.lower() else "Implicit",
            "Subcategories": subcats,
            "Subcategory_Severity": severity,
            "Bias": next((b for b in allowed_biases if b.lower() in root.children[5].answer.lower()), "No Bias"),
            "Target": next((t for t in allowed_targets if t.lower() in root.children[6].answer.lower()), "individual")
        }
    except Exception as e:
        result = {"error": f"Failed to extract from reasoning tree: {e}"}
    return result


# === Generate Counter Speech in Tamil ===
def generate_counter_speech(text, category, target_group):
    if category == "Explicit":
        prompt = (
            f"வெறுப்புப் பேச்சு: \"{text}\"\n\n"
            f"இந்த உரைக்கு சட்ட ரீதியான (IPC பிரிவுகள்) மற்றும் மரியாதையான தமிழில் எதிர்வினை (counter speech) எழுதவும்."
            f" இலக்குக் குழு: {target_group}"
        )
    else:
        prompt = (
            f"வெறுப்புப் பேச்சு: \"{text}\"\n\n"
            f"இந்த உரைக்கு எதிராக தமிழ் மொழியில் ஒரு உணர்வுபூர்வமான, மரியாதையுடனான, சமத்துவத்தை வலியுறுத்தும் பதிலை (counter speech) எழுதவும்."
            f" இலக்குக் குழு: {target_group}"
        )
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.5,
        max_tokens=256
    )
    return response.choices[0].message.content.strip()


# === Evaluation Metrics ===
from sklearn.metrics import precision_recall_fscore_support

def evaluate_prediction(pred, gold):
    pred_class = pred.get("Class", "").strip().lower()
    gold_class = gold.get("Class", "").strip().lower()

    y_pred = [1 if pred_class == "hate" else 0]
    y_true = [1 if gold_class == "hate" else 0]

    precision, recall, f1, _ = precision_recall_fscore_support(y_true, y_pred, average='binary', zero_division=0)
    return {
        "Match": y_pred[0] == y_true[0],
        "Predicted": pred_class,
        "Expected": gold_class,
        "Precision": round(precision, 2),
        "Recall": round(recall, 2),
        "F1-Score": round(f1, 2)
    }

# === MAIN EXECUTION ===
def analyze_with_tot(user_input):
    tree = build_tot_tree(user_input)
    run_tot_analysis(tree)
    result = generate_output_from_tree(tree)

    if result.get("Class") == "Hate":
        counter = generate_counter_speech(user_input, result["Category"], result["Target_Group"])
        result["Counter_Speech"] = counter
    if result.get("Class") == "Hate":
        counter = generate_counter_speech(user_input, result["Category"], result["Target_Group"])
        result["Counter_Speech"] = counter

    print(json.dumps(result, ensure_ascii=False, indent=2))
    return tree, result


# === Run & Evaluate ===
user_input = input("📥 Enter a Tamil sentence to analyze with ToT: ")
tree, result = analyze_with_tot(user_input)

# Optional: Compare against gold label if available
for entry in dataset:
    if entry["input"].strip() == user_input.strip():
        gold = entry["output"][0] if isinstance(entry["output"], list) else entry["output"]
        evaluation = evaluate_prediction(result, gold)
        print("📊 Evaluation Summary:")
        print(json.dumps(evaluation, ensure_ascii=False, indent=2))
        break

from openai import OpenAI
import json
from sklearn.metrics import precision_recall_fscore_support

# 🔐 Initialize OpenAI client
client = OpenAI(api_key="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")  # Replace with your actual API key

# === Load Dataset ===
with open("/content/drive/MyDrive/abusiveWomenDataset/July7.json", "r", encoding="utf-8") as f:
    dataset = json.load(f)

# === Enhanced Instruction Set with examples ===
instruction = """
### Hate Speech Classification Instruction

Classify the given Tamil text for hate speech. Mark as "Hate" if ANY of the following are present:

1. **Explicit Hate:** Direct attacks, insults, slurs, threats, or calls for dehumanization against individuals or groups based on gender, sexuality, identity, religion, appearance, etc.

2. **Implicit Hate:** Indirect or covert hostility, including:
    - Ridicule, public shaming, sarcasm, "mock congratulations," rhetorical questions, or dismissive tone clearly aimed at degrading, belittling, or provoking negative sentiment against the target.
    - Exaggeration, stereotype, or patronizing language where the intended meaning is to marginalize, shame, or socially isolate the person or group.
    - Generalizations that paint a group or individual as inherently inferior, foolish, or deserving of contempt, even if not using explicit hate words.

**If you are unsure, be conservative and flag for review. For ambiguous or borderline cases (mockery, coded insult, sarcasm, rhetorical shaming, etc.), consider as 'Hate' if a reasonable reader might see the message as intending to harm, degrade, or belittle the target.**

### Examples:
- "என்ன திமிரு இந்த பொண்ணுக்கு... மக்களே இன்னும் இவள் வீடியோவை பார்த்தால் உங்களை விட முட்டாள்கள் யாருமில்லை" → Hate: Mockery + Public Shaming
- "இவ மொகரை ண்டைய பாத்தால எரியுது... இல்லாத கார்த்திக்கு நம்மல போட்டு படுத்துரா" → Hate: Indirect Attack, Mockery
"""

# === Extract Allowed Labels ===
subcategories_set = set()
bias_set = set()
target_set = set()

for entry in dataset:
    output = entry["output"][0] if isinstance(entry["output"], list) else entry["output"]
    subcategories_set.update(map(str.strip, output.get("Subcategories", "").split(',')))
    bias_set.add(output.get("Bias", "").strip())
    target_set.add(output.get("Target", "").strip())

allowed_subcategories = sorted([s for s in subcategories_set if s])
allowed_biases = sorted([b for b in bias_set if b])
allowed_targets = sorted([t for t in target_set if t])

# === Tree-of-Thought Node Class ===
class ToTNode:
    def __init__(self, question, parent=None):
        self.question = question
        self.answer = None
        self.parent = parent
        self.children = []

    def add_child(self, question):
        child = ToTNode(question, parent=self)
        self.children.append(child)
        return child

    def delete_child(self, index):
        if 0 <= index < len(self.children):
            del self.children[index]

    def traverse(self, level=0):
        indent = "  " * level
        print(f"{indent}- Q: {self.question}")
        if self.answer:
            print(f"{indent}  A: {self.answer}")
        for child in self.children:
            child.traverse(level + 1)

# === GPT Reasoning Step ===
def gpt_reason(prompt):
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.4,
        max_tokens=300
    )
    return response.choices[0].message.content.strip()

# === Build Reasoning Tree with explicit mockery forced hate logic ===
def build_tot_tree(user_input):
    root = ToTNode(
        f"""கீழே ஒரு தமிழ் உரை மற்றும் அது தொடர்பான பன்முக கேள்விகள் உள்ளன. கீழே உள்ள வழிமுறையின் அடிப்படையில் பதில் அளிக்கவும்.

### வழிமுறை (Instruction):
{instruction}

### உரை (Input):
{user_input}
"""
    )
    # Step 1: Check sarcasm/mockery etc.
    root.add_child(
        "படி 1: கீழ்காணும் எந்த வகைகளில் உள்ளதா என்று முதல் பதிலில் கட்டாயமாக எழுதவும் (ஆம்/இல்லை, எது?): "
        "1) நேரடி பாகுபாடு/வெறுப்பு 2) இரகசிய/நிகழ்வுசார் பாகுபாடு 3) நையாண்டி (sarcasm)/மோக்கிங் (mocking)/கீழ்த்தரமான கேள்வி (rhetorical shaming)/பொது அவமானம் (public shaming)/பெண்கள், ஆண்கள், LGBTQ+, அமைப்புகள், பிறர் மீது, "
        "பெயர்ச்சொல்லாக (implicit) அல்லது வெளிப்படையாக (explicit) இருந்தால், குறிப்பிடவும்."
    )
    root.add_child("படி 2: இலக்குக் குழு யார்? Women, Men, LGBTQ+, Organization, அல்லது Others என்பதிலிருந்து தேர்ந்தெடுக்கவும்.")
    root.add_child(
        "படி 3: இந்த உரையில் வெறுப்புப் பேச்சு உள்ளதா? ஏன்? "
        "முன்பு பதிலளித்த நையாண்டி/மோக்கிங்/கீழ்த்தரமான கேள்வி/பொது அவமானம் வகைகளில் ஏதேனும் இருந்தால், "
        "'Hate' என்று வகைப்படுத்தவும், ஏனெனில் என்று விளக்கவும்."
    )
    root.add_child("படி 4: Explicit அல்லது Implicit? விளக்கவும்.")
    root.add_child(f"படி 5: பொருத்தமான துணைப் பிரிவுகளை மட்டும் கீழே உள்ள பட்டியலிலிருந்து தேர்வு செய்யவும். JSON format-இல் பதிலளிக்கவும்: {json.dumps(allowed_subcategories)}")
    root.add_child(f"படி 6: படி 5ல் தேர்வு செய்யப்பட்ட ஒவ்வொரு துணைப் பிரிவுக்கும் தீவிரத்தன்மையை Low, Mild, High, Severe என வகைப்படுத்தவும். JSON வடிவில் பதிலளிக்கவும்.")
    root.add_child(f"படி 7: பாகுபாடு உள்ளதா? இருப்பின் {', '.join(allowed_biases)} என்பதிலிருந்து தேர்வு செய்யவும் மற்றும் விளக்கவும்.")
    root.add_child(f"படி 8: இலக்கு ஒரு தனிநபரா அல்லது குழுவா? கீழ்காணும் ஒன்றிலிருந்து தேர்வு செய்யவும்: {', '.join(allowed_targets)}.")
    return root

# === Fill the Reasoning Tree ===
def run_tot_analysis(root):
    for child in root.children:
        prompt = f"{root.question}\n\n{child.question}"
        child.answer = gpt_reason(prompt)

# === Extract Final Result with forced 'Hate' override if mockery/sarcasm detected ===
def generate_output_from_tree(root):
    try:
        try:
            subcats = json.loads(root.children[4].answer.strip())
            subcats = [s for s in subcats if s in allowed_subcategories]
        except:
            subcats = []

        try:
            severity_map = json.loads(root.children[5].answer.strip())
            severity = {k: v for k, v in severity_map.items() if k in subcats}
        except:
            severity = {}

        # Check if Step 1 answer indicates sarcasm/mocking etc.
        mockery_detected = False
        step1_answer = root.children[0].answer.lower()
        # Simple heuristic keywords, can be extended
        mockery_terms = [
            'sarcasm', 'mocking', 'rhetorical', 'shaming', 'public shaming',
            'நையாண்டி', 'மோக்கிங்', 'கீழ்த்தரமான கேள்வி', 'பொது அவமானம்'
        ]
        if any(term in step1_answer for term in mockery_terms):
            mockery_detected = True

        # Normally get the class
        predicted_class = "Hate" if "yes" in root.children[2].answer.lower() else "Non-Hate"

        # Override to Hate if mockery detected regardless of Step 3 output
        final_class = "Hate" if mockery_detected else predicted_class

        result = {
            "Target_Group": next((g for g in ["Women", "Men", "LGBTQ+", "Organization", "Others"] if g.lower() in root.children[1].answer.lower()), "Others"),
            "Class": final_class,
            "Category": "Explicit" if "explicit" in root.children[3].answer.lower() else "Implicit",
            "Subcategories": subcats,
            "Subcategory_Severity": severity,
            "Bias": next((b for b in allowed_biases if b.lower() in root.children[6].answer.lower()), "No Bias"),
            "Target": next((t for t in allowed_targets if t.lower() in root.children[7].answer.lower()), "individual")
        }
    except Exception as e:
        result = {"error": f"Failed to extract from reasoning tree: {e}"}
    return result

# === Generate Counter Speech in Tamil ===
def generate_counter_speech(text, category, target_group):
    if category == "Explicit":
        prompt = (
            f"வெறுப்புப் பேச்சு: \"{text}\"\n\n"
            f"இந்த உரைக்கு சட்ட ரீதியான (IPC பிரிவுகள்) மற்றும் மரியாதையான தமிழில் எதிர்வினை (counter speech) எழுதுவ ILகுக் குழு: {target_group}"
        )
    else:
        prompt = (
            f"வெறுப்புப் பேச்சு: \"{text}\"\n\n"
            f"இந்த உரைக்கு எதிராக தமிழ் மொழியில் ஒரு உணர்வுபூர்வமான, மரியாதையுடனான, சமத்துவத்தை வலியுறுத்தும் பதிலை (counter speech) எழுதவும்."
            f" இலக்குக் குழு: {target_group}"
        )
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.5,
        max_tokens=256
    )
    return response.choices[0].message.content.strip()

# === Evaluation Metrics ===
def evaluate_prediction(pred, gold):
    pred_class = pred.get("Class", "").strip().lower()
    gold_class = gold.get("Class", "").strip().lower()
    y_pred = [1 if pred_class == "hate" else 0]
    y_true = [1 if gold_class == "hate" else 0]
    precision, recall, f1, _ = precision_recall_fscore_support(y_true, y_pred, average='binary', zero_division=0)
    return {
        "Match": y_pred[0] == y_true[0],
        "Predicted": pred_class,
        "Expected": gold_class,
        "Precision": round(precision, 2),
        "Recall": round(recall, 2),
        "F1-Score": round(f1, 2)
    }

# === MAIN EXECUTION ===
def analyze_with_tot(user_input):
    tree = build_tot_tree(user_input)
    run_tot_analysis(tree)
    result = generate_output_from_tree(tree)
    if result.get("Class") == "Hate":
        counter = generate_counter_speech(user_input, result["Category"], result["Target_Group"])
        result["Counter_Speech"] = counter
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return tree, result

# === Run & Evaluate ===
user_input = input("📥 Enter a Tamil sentence to analyze with ToT: ")
tree, result = analyze_with_tot(user_input)

# Optional: Compare against gold label if available
for entry in dataset:
    if entry["input"].strip() == user_input.strip():
        gold = entry["output"][0] if isinstance(entry["output"], list) else entry["output"]
        evaluation = evaluate_prediction(result, gold)
        print("📊 Evaluation Summary:")
        print(json.dumps(evaluation, ensure_ascii=False, indent=2))
        break

